routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', 'PostController@index')->name('index');
Route::get('/post/{slug}', 'PostController@show')->name('post');
Route::get('/categories/{slug}', 'CategoryController@show')->name('category');

Route::get('/series/', 'SeriesController@index')->name('series_list');
Route::get('/series/{slug}', 'SeriesController@show')->name('series_post_list');

Route::get('/tags/{slug}', 'TagController@show')->name('tag');

Route::post('/comment/{post}', 'CommentController@store')->name('post_comment');
Route::post('/comment/edit/{post}', 'CommentController@update')->name('edit_comment');

Route::get('/search', 'SearchController@index')->name('search');
Auth::routes();

Route::prefix('admin')
    ->name('admin.')
    ->middleware(['auth', 'permission:access admin'])
    ->group(function() {

        Route::get('/', 'HomeController@index')->name('home');

        Route::get('/meta', 'MetaAdmin@index')->name('meta_list');
        Route::get('/meta/{value}', 'MetaAdmin@show')->name('meta_admin');
        Route::post('/meta/{value}/', 'MetaAdmin@store')->name('meta_create');

        Route::get('/posts', 'PostAdmin@index')->name('posts');
        Route::get('/posts/{slug}', 'PostAdmin@show')->name('post_edit');
        Route::post('/posts/{slug}', 'PostAdmin@update')->name('post_update');

        Route::get('/permissions', 'PermissionController@index')->name('permission_list');
        Route::post('/permissions/create', 'PermissionController@store')->name('permission_create');

        Route::get('/roles', 'RoleController@index')->name('role_list');
        Route::post('/roles/create', 'RoleController@store')->name('role_create');

        Route::get('/users/', 'UserController@index')->name('user_admin');
        Route::get('/users/{id}', 'UserController@show')->name('user_edit');
        Route::post('/users/{id}', 'UserController@update')->name('user_update');

        Route::get('/comments', 'CommentController@index')->name('comments_admin');
        Route::get('/comments/{id}', 'CommentController@edit')->name('comments_edit');
    });

resources/views/admin/categories.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <a href="{{route('admin.home')}}">back</a>
        <table>
            <thead>
                <tr>
                    <td> category name</td>
                    <td> category slug</td>
                </tr>
            </thead>
            @if(count( $categories ))
                @foreach( $categories as $category)
                    <tr>
                        <td> {{ $category->name}}</td>
                        <td> {{ $category->slug}}</td>
                        <td> <a href="{{ route('admin.category_delete',
                        $category->slug)}}" > delete </a></td>
                    </tr>
                @endforeach
            @endif
        </table>
        <form method="post" action="{{ url('/admin/categories/') }}">
            @csrf
            <label for="name">Category
                <input type="text" name="name" id="name">
            </label>
            <input type="submit" value="Add category">
        </form>

    </div>
    <script type="text/javascript">
        let btn = document.querySelectorAll('.delcat');
btn = Array.from(btn);
btn.map(function(b) {
    b.addEventListener('click', function(e) {
        fetch('/admin/categories', {method: 'DELETE'});
    });
});
    </script>
@endsection

resources/views/admin/comment.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
	<a href="{{route('admin.home')}}">back</a>
	<form method="post"
	      action="{{route('edit_comment',  $comments->getPost($comments)->slug )}}">
	    @csrf
	    <textarea>{{$comments->comment}}</textarea>
	    <input type="hidden" value="{{ $comments->id }}" name="id">
	    <input type="submit">
	</form>
    </div>
@endsection

resources/views/admin/comments.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <a href="{{route('admin.home')}}">back</a>
        <table>
            <thead>
                <tr>
                    <td>Post Name</td>
                    <td>User</td>
                    <td>Comment excerpt</td>
                    <td colspan=2>Actions</td>
                </tr>
            </thead>
            @foreach( $comments as $comment)
                <tr>
                    <td>
                        <a href="{{ route('post', $comment->getPost($comment)->slug )}}">
                            {{ $comment->getPost($comment)->title }}
                        </a>
                    </td>
                    <td>
                        <a href="{{ route('admin.user_edit', $comment->user()->first()->id )}}">
                            {{ $comment->user()->first()->name }}
                        </a>
                    </td>
                    <td>
                        {!! $comment->excerpt($comment->comment) !!}
                    </td>
                    <td>
                        <a href="{{ route('admin.comments_edit', $comment->id
                        )}}">edit </a>
                    </td>
                    <td>
                        <delete-btn url="{{ route('admin.comments_delete',
                        $comment->id )}}"></delete-btn>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection

resources/views/admin/home.blade.php
@extends('layouts.admin')

@section('content')
    <div class="dashboard">
        <ul>
            <li>
                <a href="{{ route('admin.posts') }}"> manage posts</a>
            </li>
            <li>
                <a href="{{ route('admin.meta_admin', 'category') }}"> manage categories</a>
            </li>
            <li>
                <a href="{{ route('admin.meta_admin', 'tag') }}"> manage tags</a>
            </li>
            <li>
                <a href="{{ route('admin.meta_admin', 'series') }}"> manage series</a>
            </li>
        </ul>
    </div>
<passport-clients></passport-clients>
<passport-authorized-clients></passport-authorized-clients>
<passport-personal-access-tokens></passport-personal-access-tokens>

@endsection

resources/views/admin/meta.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <a href="{{route('admin.home')}}">back</a>
        <table>
            <thead>
                <tr>
                    <td> {{ $meta_name}} name</td>
                    <td> {{ $meta_name}} slug</td>
                    <td colspan="2">Actions</td>
                </tr>
            </thead>
            @if(count( $meta ))
                @foreach( $meta as $m)
                    <tr>
                        <td> {{ $m->name}}</td>
                        <td> {{ $m->slug}}</td>
                        <td> <delete-btn url="{{ route('api.meta_delete',
                        [strtolower( $meta_name ), $m->slug ])}}" > </delete-btn></td>
                    </tr>
                @endforeach
            @endif
        </table>
        <form method="post" action="{{ route('admin.meta_create',
        strtolower( $meta_name )) }}">
            @csrf
            <label for="name">{{ $meta_name }}
                <input type="text" name="name" id="name">
            </label>
            <input type="submit" value="Add {{$meta_name}}">
        </form>
    </div>
@endsection

resources/views/admin/permissions.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <a href="{{route('admin.home')}}">back</a>
        <table>
            <thead>
                <tr>
                    <td> {{ $meta_name}} name</td>
                    <td> {{ $meta_name}} slug</td>
                    <td colspan="2">Actions</td>
                </tr>
            </thead>
            @if(count( $meta ))
                @foreach( $meta as $m)
                    <tr>
                        <td> {{ $m->name}}</td>
                        <td> {{ $m->slug}}</td>
                        <td> <a href="{{ route('admin.meta_delete',
                        [ 'category', $m->slug ] )}}" > delete </a></td>
                    </tr>
                @endforeach
            @endif
        </table>
        @if ( $errors->any() )
            @foreach($errors->all() as $error)
                {{ $error }}
            @endforeach
        @endif
        <form method="post" action="{{ route($action_url,
        strtolower( $meta_name )) }}">
            @csrf
            <label for="name">{{ $meta_name }}
                <input type="text" name="name" id="name">
            </label>
            <input type="submit" value="Add {{$meta_name}}">
        </form>
    </div>
@endsection

resources/views/admin/post.blade.php
@extends('layouts.admin')

@section('content')
    <div class="content">
        <a href="{{route('admin.home')}}">back</a>
        <form method="post" action="{{ route('admin.post_update',
        $post->slug)}}">
        @csrf
        <div class="form-group">
            <label for="post_title">Post Title</label>
            <input type="text" name="post_title" value="{{ $post->title }}">

        </div>
        <div>
            <strong>Post Slug:</strong> {{ $post->slug }}
        </div>

        <div>
            @if($post->categories())
                <h2>Categories</h2>
                <ul>
                    @foreach($categories as $cat)
                        <li>
                            @if($post->categories()->where('name',
                                $cat->name)->first())
                                <input type="checkbox"
                                       name="category_select[]" value="{{
                                       $cat->slug}}" checked> {{ $cat->name}}
                                   @else

                                       <input type="checkbox"
                                              name="category_select[]" value="{{
                                              $cat->slug}}"> {{ $cat->name}}
                                          @endif
                        </li>
                    @endforeach
                </ul>
            @endif
            <div>
                @if(count( $post->categories()->get()->toArray() ) > 1)
                    <h2> Applied Categories </h2>
                    @if (count($post->categories()->get()) > 1)
                        @foreach($post->categories()->get() as $pcat)
                            {{ $pcat->name}},
                        @endforeach
                    @else
                        {{ $post->categories()->first()->name }}
                    @endif
                @endif
            </div>
        </div>
        <div>
            @if ($post->tags())
                <h2>Tags</h2>
                <ul>
                    @foreach($tags as $tag)
                        <li>
                            @if($post->tags()->where('name',
                                $tag->name)->first())
                                <input type="checkbox"
                                       name="tag_select[]" value="{{
                                       $tag->slug}}" checked> {{ $tag->name}}
                                   @else

                                       <input type="checkbox"
                                              name="tag_select[]" value="{{
                                              $tag->slug}}"> {{ $tag->name}}
                                          @endif
                        </li>
                    @endforeach
                </ul>
                @endif
                <div>
                    @if (count( $post->tags()->get()->toArray() ) > 1)
                        <h2> Applied Tags </h2>
                        @if (count($post->tags()->get()) > 1)
                            @foreach($post->tags()->get() as $ptag)
                                {{ $ptag->name}}
                            @endforeach
                        @else
                            {{ $post->tags()->first()->name }}
                        @endif
                    @endif
                </div>
        </div>
        <div>
            <h2>Series</h2>
            <ul>
                @foreach($series as $s)
                    <li>
                        @if($post->series()->where('name',
                            $s->name)->first())
                            <input type="checkbox"
                                   name="series_select[]" value="{{
                                   $s->slug}}" checked> {{ $s->name}}
                               @else

                                   <input type="checkbox"
                                          name="segory_select[]" value="{{
                                          $s->slug}}"> {{ $s->name}}
                                      @endif
                    </li>
                @endforeach
            </ul>
            <div>
                <h2> Applied Series </h2>
                @foreach($post->series()->get() as $pseries)
                    {{ $pseries->name}}
                @endforeach
            </div>
        </div>
        <input type="submit" value="update">
        </form>
    </div>
@endsection

resources/views/admin/posts.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <a href="{{route('admin.home')}}">back</a>
        <table>
            <thead>
                <tr>
                    <td> Post Name</td>
                    <td> Post Slug</td>
                    <td colspan="2"> Actions</td>
                </tr>
            </thead>
            @foreach( $posts as $post)
                <tr>
                <td><a href="{{ route('post', $post->slug)}}"> {{
                $post->title}}</a></td>
                    <td> {{ $post->slug}}</td>
                    <td> <a href="{{ route('admin.post_edit',
                    $post->slug)}}" > edit </a></td>
                    <td> <delete-btn url="{{ route('api.post_delete',
                    $post->slug)}}" > </delete-btn></td>
                </tr>

            @endforeach
        </table>
    </div>
@endsection

resources/views/admin/user_details.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <a href="{{route('admin.home')}}">back</a>
        <h2>{{ $user->name }}</h2>
        {{ $user->api_token }}
        <form class="permissions" method="post" action="{{
        route('admin.user_update', $user->id) }}">
        @csrf
        <h2> Available Roles </h2>
        <ul>
            @foreach($roles as $role)
                @if( in_array($role->name, $userRoles) )
                    <li> {{ $role->name }}

                        <input type="radio"
                               value="{{ $role->name }}"
                               name="role" checked >
                    </li>
                @else
                    <li> {{ $role->name }}
                        <input type="radio"
                               value="role['{{ $role->name }}']"
                               name="role" >
                    </li>
                @endif
            @endforeach
        </ul>
        <h2> Available Permissions </h2>
        <ul>
            @foreach($permissions as $permission)
                @if( in_array($permission->name, $userPerms) )
                    <li>
                        {{ $permission->name }}
                        <input type="checkbox"
                               value="{{ $permission->name }}"
                               name="permission[]" checked >

                    </li>
                @else
                    <li>
                        {{ $permission->name }}
                        <input type="checkbox"
                               value="{{ $permission->name }}"
                               name="permission[]">
                    </li>
                @endif
            @endforeach
        </ul>
        <input type="submit">
        </form>
    </div>
@endsection

resources/views/admin/user_list.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <a href="{{route('admin.home')}}">back</a>
        <table>
            <thead>
                <tr>
                    <td> user name</td>
                    <td> roles</td>
                    <td colspan="2">Actions</td>
                </tr>
            </thead>
            @if(count( $users ))
                @foreach( $users as $user)
                    <tr>
                        <td> {{ $user->name}}</td>
                        <td>
                            @foreach( $user->roles as $role )
                                {{ $role->name }}
                            @endforeach
                        </td>
                        <td> <a href="{{ route('admin.user_edit', $user->id)}}" > edit </a></td>
                    </tr>
                @endforeach
            @endif
        </table>
    </div>
@endsection